language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - hieua2m@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: WxTrS/qsiGX8SUS4leT7Eedble4iJ79IjX0MqfofVqof1OiESyE+YXRnvVQIFpTuxzHK27fUKEYCwxpOl6Qq+yUvmF4C0SVSlcJEJfuVsUJs+HLZ9X0137jmHXvJaCgjfpMCQfx2H9pbagGtp7PBajNn+F27ZR49jEXfU7Pp5omXygqrli1sVpwspaWy1nLiOcxPnoznNMzXLA5u3m5rSQ6Alewv6P13zlqQJS/f6MMMfwZUPG6rnY8AC0bZZbtycRF91GqpXCaFIETD2u1S/hEsPmAioxsnd0mj2AvvjHjHvdIyOaDs1YCljB3dcC+9ydro1zU31nFLLpcSrVMOZ6zEUgHGTQ5kXKr7FS7Qe8ISRXaeqc+0vo5LivMP42AL6qYhcp1d7Z+ESnt28EKlHsYcON3T0Um1+SakDLDuDAC4B89tVawOFekG6RwdwhOIGvmXaJqI3OJ9ZrfVaP4QNg+R4CPxtMh8jco4KNxBWWHyUdgedqhMweFJKrmySUGaX8hxnhFounxxHOZw+L4qrZvlKkcczogF+WnBLSyyPwkBvXCkz+mAfgIr5GbejveQEXliWoDbefIintYZcIgodVTbhuge6haxMPpnrqlcT2ziW4Ht4cKjCqCvV9sdWJ8ZWpGeRDFOoiO4LdEPFtdQ5N7EUSQPVGcY34RZ2JwHlTo=
  - secure: sigRZ8IZerx5sY8ENLfl6NlFpQOt01lSl9fvhI7kCMw6VNFvH1PxEy4x183hFSmLxkuyH4JkeAKMqYbELPusp+HslGl2TB3EUHlpMgQzFgsl4PDG00XTUTA4be6iRJSNrb7edBw7S/aPd/V1a/WOC8rCeTiu4LtVx2gTwRaBFQAhI+OPS8qk1uIx7zLNwSwxZEtzUK/SfbWxb2Tb/LH/dNT4XYZ5TL+PEI6H2C0HzTBDW0s5G6d60SZb5pGdPTWJROaOrUfFiyPPXy12NuqlUoh5ltrjr0fyGbA8f1WaNhjIUOewWcxulh0HtsiZXcO4yKXnRrQW2dLBZmtaVsqT1zIRHJ6djkCwZkLZMlTSyBRfmkgmvjp60WkIonT6hTUZYbK9iu4g+FZevLxRwdcnBYpV+otcBmEpKGxvT36wfqW7Pvd7slWF2IcrTMDt/PH4ll4GUq5XpBttECkTdpa8rLHgpStVxAN2Xv0jDwisvFDPjdBaRGRHuxufnViokiDStuUuhdZGs0a6U9pdrcdcsKLvKVarhHTnWvnRkMkRKJaKyAXxXLCrvFSQCDFS1kbpzlU8f70f1NHUJ/YBuqmwYEfJVfWgxnH1Km5y2FM5PaiaaDp80160ac9BZSPJEa2Ecv/ArZ5rocw+JD9zGOP9NV3PVo0zYs2TNUcMuRW7ULY=
  - secure: L5e9mo1VK+FnhOreS+0xoro7LgS2aJJeFRmUTfvXPZ/xf/CrjWVo7KIaTCk9tnYoD4lFQo3iMAzJYhKkmbkPa9IlGAUM9BK+Fx4d2kGwODTpKXi2F1NbZ6FhK5bTVI6Cx22BFfLARpbWZltNfycQ6gXH9e3cDffKk1pqv8Tf1TvCcqdXhxgZFgdTPWxH97gyCIOIV9vDZfuvl7T7hiMBqXbmxkkYdUCivHIee26kIhIoFHLy/mv6LVImXVjsV9G2NA6t7FkNJO9dPgiHATNmBW/ynsrJbwkPROloX7ohvOCsbQK/I2ZGwvYWVWxNrWkLoMbL2D+0l27Dvwsjp4J2irJTFCR0WrDLbzviBGlzn6HCY2KWkOBXSLt8MweIFQbNP48wMj17ptlJzXZPo3rOvHRyTDtmSjP3VauZJdQpdZYzKoE1C0Gl5DyQXK0YASoWwNoaiMAoI/+JRn3jjthbc8oCGpflu9Vve4uslLH5628AbX3HliliaUG3TOkNfgTmwDaEZNiCgXfHKX6b76s0O2oYhhbknx3SlnUcgo3IQEluG7L0zz0Ozh20szUk5J6a1JvznzcW8qcGLvdlbhv0ado3nIJtF03gQY6GZoZjuRZ4rKcXE0rvHB33NCR34mCnfdfTHBKW3QO9PB+fdi3pCsfjw3pDrllI6IuP5OcYCBU=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
