language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - hieua2m@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
   #Token
  - secure: L5e9mo1VK+FnhOreS+0xoro7LgS2aJJeFRmUTfvXPZ/xf/CrjWVo7KIaTCk9tnYoD4lFQo3iMAzJYhKkmbkPa9IlGAUM9BK+Fx4d2kGwODTpKXi2F1NbZ6FhK5bTVI6Cx22BFfLARpbWZltNfycQ6gXH9e3cDffKk1pqv8Tf1TvCcqdXhxgZFgdTPWxH97gyCIOIV9vDZfuvl7T7hiMBqXbmxkkYdUCivHIee26kIhIoFHLy/mv6LVImXVjsV9G2NA6t7FkNJO9dPgiHATNmBW/ynsrJbwkPROloX7ohvOCsbQK/I2ZGwvYWVWxNrWkLoMbL2D+0l27Dvwsjp4J2irJTFCR0WrDLbzviBGlzn6HCY2KWkOBXSLt8MweIFQbNP48wMj17ptlJzXZPo3rOvHRyTDtmSjP3VauZJdQpdZYzKoE1C0Gl5DyQXK0YASoWwNoaiMAoI/+JRn3jjthbc8oCGpflu9Vve4uslLH5628AbX3HliliaUG3TOkNfgTmwDaEZNiCgXfHKX6b76s0O2oYhhbknx3SlnUcgo3IQEluG7L0zz0Ozh20szUk5J6a1JvznzcW8qcGLvdlbhv0ado3nIJtF03gQY6GZoZjuRZ4rKcXE0rvHB33NCR34mCnfdfTHBKW3QO9PB+fdi3pCsfjw3pDrllI6IuP5OcYCBU=
#DOCKER_USERNAME
  - secure: HPAeDLOaWepzkwPvdrCw1Z5LbnkAomWQtW5aXc2b/G28R6XUIY8+y8yuXXhBEwrNvL9VtbHN989J5F10HkCKepIJhkGYRrtMnW/2o56vKqiNHJsjjtXLvP/KrHmf/GA+WDd9yx2dyR+niA4bkCRcpXavg6CHTbYtJU6szyouOIKLm1FXWNQA1qBNFJz56IEtfuvlowlM3UbRhztXlbiDa5q9oMbxA821Va6UXLnOQx+P3p1fCaZ6nxPZzDNjldLiQIlXkrgVpjzpzi+AhWfE77qenAMMy0nywel5eJieVBDWf2oXYUyZHuDiknxtoNH7YyqAzNOHJCDcqc/54IvtlOo5P3WaKBM4LeVPuMjKHFcmSGPxp7g+iTDxzS6jr/73bWVN4YmjlJd14cilZv1FdFWdneVxI7hKJju+VI1CxxGds+EQJ8JB5nI5M9E/sKbTsyGRHJH/Sq7c3rmv8PFzlyUy3HKvd75Gzz5bF8ujozfmbehx+T2qRY8ZciuwxvigXMcebzs2sbIn6e89P4c6yGtiteLsERdnI1sHa6TqQheR9HeSRlO9FbS6Zb8JkyoKMzMsLoKpSKNQZYk7J6XIBpF4tQoJLY+YaY3Hb2WDStKHN0pvPu6h7RMurwdP+H7mFYuzbR6IjuMnqXqbbPcLYdxVpJdZH+406o2URyznfYo=
#DOCKER_PASSWORD
  - secure: e/F1A2e6kirPXpAmfbAZyO9tHR+jtJb7M2AQ/o9p32cULAWdJC/hfcmEhek3Cl8u3qXvrV0TySS+LgNOdQepUeSv30hk6MBkhxSqdwmxz6FcjABMlNpMP6HbEngYmObi4z0fpgX45x/sMDeKeXgzFyDs53q1CVFP3BvzSd2on3pY1mcKB9HVvBIgacOJtcd/uqTpwycizyzX9ZcSCxi0qbqyqBSDLe4ydu1O3xJsbPO1pm0o5Q3PWUlSeV3nLSaHdmvY8GzDkUw6cRBQ9Z4V0r6CixekX0FTl07oiWDS6HMBr65BJQrbFbdutiBDJIf7bGHUwLVgDkzahvok2oMi+IlVcvb1hlVvTIR35FjpUyVDl7MnU2kMa5KlI25/vFFHel9dXlj/ui62YQHGY2DeBIjZrRmkrcfQOogjVbYlv/oI5ipE1Qle33WnGBhkuaP/EaQ0mb8Rt2Z8DaWVEkA8+uIL/rp2ctJgxOYGpmCjHIhV/PGRN645acYm1Vy6/v4Fv7vCSs6MMFE7oBBIflpGZPVbxeM/UsH77rlPK9Y6r8YlvZcp3oaZ0HP74fPeWjbAUaFliPntz067hQN6zZVWtDCqCfIwGLDryfsikMEnsLTsVj9yShx1cgGDhnVSv5bD63IUQgjEvNEkYUllasaZUFZzlzLhnyr3o597EfLNsDY=
before_install:
- gem install travis -v 1.8.10 --no-document
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
